name: Generate Allure Report

on:
  push:
    paths:
      - "allure-results/**"
  workflow_dispatch:

jobs:
  Generate_Report:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Restore History
        run: |
          mkdir -p allure-results/history
          if [ -d allure-report/history ]; then
            cp -r allure-report/history allure-results/
          fi

      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline --save-dev

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Save History
        run: |
          mkdir -p allure-report/history
          cp -r allure-report/history allure-results/

      - name: Upload Allure Report Artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./allure-report

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
